import type { Dish } from "../components/DishCard";

export const menuData: Dish[] = [

  // ─── SOUPS ───────────────────────────────────────────────────────────────
  {
    id: "soup-1",
    title: "Tomato Soup (Sweet)",
    teluguTitle: "టొమాటో సూప్",
    category: "SOUPS",
    description: "Creamy, sweet and tangy tomato soup garnished with golden butter croutons and fresh cream.",
    price: "160 / 190",
    rating: 4.2,
    image: "/images/tomato-soup.jpg",
    isPopular: true,
    ingredients: ["Fresh Tomatoes", "Cream", "Butter", "Croutons", "Herbs"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "10 mins"
  },
  {
    id: "soup-2",
    title: "Sweet Corn Soup",
    teluguTitle: "స్వీట్ కార్న్ సూప్",
    category: "SOUPS",
    description: "Thick, comforting sweet corn soup with tender corn kernels in a light vegetable broth.",
    price: "160 / 190",
    rating: 4.1,
    image: "/images/sweet-corn-soup.jpg",
    ingredients: ["Sweet Corn", "Cornflour", "Vegetable Stock", "Pepper"],
    prepTime: "10 mins"
  },
  {
    id: "soup-3",
    title: "Veg. Corn Soup (Sweet)",
    teluguTitle: "వెజ్ కార్న్ సూప్",
    category: "SOUPS",
    description: "Wholesome vegetable and sweet corn soup blended with mild spices and fresh veggies.",
    price: "160 / 190",
    rating: 4.0,
    image: "/images/veg-corn-soup.png",
    ingredients: ["Mixed Vegetables", "Sweet Corn", "Stock", "Herbs"],
    prepTime: "12 mins"
  },
  {
    id: "soup-4",
    title: "Veg. Hot & Sour Soup",
    teluguTitle: "హాట్ అండ్ సోర్ సూప్",
    category: "SOUPS",
    description: "Spicy and tangy thick vegetable broth with mushrooms, bamboo shoots, and spring onions.",
    price: "180 / 210",
    rating: 4.3,
    image: "/images/veg-hot-sour-soup.jpg",
    ingredients: ["Cabbage", "Mushrooms", "Vinegar", "Soy Sauce", "Chilli"],
    allergens: ["Soy", "Gluten"],
    prepTime: "12 mins"
  },
  {
    id: "soup-5",
    title: "Mushroom Soup",
    teluguTitle: "మష్రూమ్ సూప్",
    category: "SOUPS",
    description: "Velvety cream of mushroom soup with sautéed button mushrooms and aromatic herbs.",
    price: "180 / 210",
    rating: 4.2,
    image: "/images/mushroom-soup.jpg",
    ingredients: ["Button Mushrooms", "Cream", "Butter", "Thyme", "Stock"],
    allergens: ["Dairy"],
    prepTime: "12 mins"
  },
  {
    id: "soup-6",
    title: "Veg. Manchow Soup",
    teluguTitle: "వెజ్ మంచో సూప్",
    category: "SOUPS",
    description: "Indo-Chinese style thick soup with crispy noodles, mixed veggies and dark soy broth.",
    price: "180 / 210",
    rating: 4.3,
    image: "/images/veg-manchow-soup.png",
    ingredients: ["Mixed Vegetables", "Fried Noodles", "Soy Sauce", "Chilli Sauce"],
    allergens: ["Soy", "Gluten"],
    prepTime: "14 mins"
  },
  {
    id: "soup-7",
    title: "Cream of Mushroom Soup (Sweet)",
    teluguTitle: "క్రీమ్ ఆఫ్ మష్రూమ్ సూప్",
    category: "SOUPS",
    description: "A rich, sweet, creamy blended mushroom bisque with a drizzle of fresh cream.",
    price: "180 / 210",
    rating: 4.1,
    image: "/images/cream-of-mushroom-soup.png",
    ingredients: ["Mushrooms", "Cream", "Butter", "Flour"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "12 mins"
  },
  {
    id: "soup-8",
    title: "Lemon Coriander Soup",
    teluguTitle: "నిమ్మ కొత్తిమీర సూప్",
    category: "SOUPS",
    description: "Light and refreshing clear soup with fresh lemon juice, tender veggies, and aromatic coriander.",
    price: "160 / 190",
    rating: 4.2,
    image: "/images/lemon-coriander-soup.jpg",
    ingredients: ["Lemon Juice", "Coriander", "Mixed Vegetables", "Stock"],
    prepTime: "10 mins"
  },
  {
    id: "soup-9",
    title: "Veg. Clear Soup",
    teluguTitle: "వెజ్ క్లియర్ సూప్",
    category: "SOUPS",
    description: "Simple, healthy and light vegetable clear broth with julienned vegetables and mild seasoning.",
    price: "160 / 190",
    rating: 4.0,
    image: "/images/veg-clear-soup.jpg",
    ingredients: ["Mixed Vegetables", "Vegetable Stock", "Pepper", "Salt"],
    prepTime: "8 mins"
  },

  // ─── STARTERS ────────────────────────────────────────────────────────────
  {
    id: "starter-1",
    title: "Wet Manchuria",
    teluguTitle: "వెట్ మంచూరియా",
    category: "STARTERS",
    description: "Golden fried veggie balls served with a generous ladle of spicy, tangy Manchurian gravy.",
    price: 340,
    rating: 4.4,
    image: "/images/wet-manchuria.jpg",
    isPopular: true,
    ingredients: ["Cabbage", "Carrots", "Ginger", "Garlic", "Soy Sauce", "Chilli"],
    allergens: ["Soy", "Gluten"],
    prepTime: "15 mins"
  },
  {
    id: "starter-2",
    title: "Veg. Manchuria Dry",
    teluguTitle: "వెజ్ మంచూరియా డ్రై",
    category: "STARTERS",
    description: "Crispy fried vegetable balls tossed dry with bold chilli-garlic sauce and spring onions.",
    price: "300 / 240",
    rating: 4.3,
    image: "/images/veg-manchuria-dry.jpg",
    ingredients: ["Mixed Veggies", "Garlic", "Chilli Sauce", "Spring Onion"],
    allergens: ["Soy", "Gluten"],
    prepTime: "15 mins"
  },
  {
    id: "starter-3",
    title: "Gobhi Manchuria",
    teluguTitle: "గోబీ మంచూరియా",
    category: "STARTERS",
    description: "Crispy cauliflower florets tossed in a spicy Manchurian sauce with spring onions and chilli.",
    price: 300,
    rating: 4.2,
    image: "/images/gobi-manchuria.jpg",
    ingredients: ["Cauliflower", "Soy Sauce", "Ginger-Garlic", "Spring Onion"],
    allergens: ["Soy", "Gluten"],
    prepTime: "15 mins"
  },
  {
    id: "starter-4",
    title: "Paneer Majestic",
    teluguTitle: "పనీర్ మెజెస్టిక్",
    category: "STARTERS",
    description: "Crispy paneer strips marinated in tangy curd batter, fried and tossed in spicy sauce.",
    price: 310,
    rating: 4.5,
    image: "/images/paneer-majestic.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Curd", "Spices", "Curry Leaves", "Chilli"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "starter-5",
    title: "Schezwan Manchuria",
    teluguTitle: "షెజ్వాన్ మంచూరియా",
    category: "STARTERS",
    description: "Veggie balls fried and tossed in fiery Schezwan sauce for extra heat and bold flavour.",
    price: 320,
    rating: 4.3,
    image: "/images/schezwan-manchuria.jpg",
    ingredients: ["Mixed Veggies", "Schezwan Sauce", "Garlic", "Chilli"],
    allergens: ["Soy", "Gluten"],
    prepTime: "16 mins"
  },
  {
    id: "starter-6",
    title: "Paneer Manchuria",
    teluguTitle: "పనీర్ మంచూరియా",
    category: "STARTERS",
    description: "Juicy paneer pieces fried and tossed in sweet-spicy Manchurian sauce with fresh veggies.",
    price: 320,
    rating: 4.5,
    image: "/images/paneer-manchuria.jpg",
    ingredients: ["Paneer", "Soy Sauce", "Garlic", "Capsicum", "Spring Onion"],
    allergens: ["Dairy", "Soy"],
    prepTime: "16 mins"
  },
  {
    id: "starter-7",
    title: "Soya Chaap Manchuria",
    teluguTitle: "సోయా చాప్ మంచూరియా",
    category: "STARTERS",
    description: "Soya chaap pieces fried crispy and tossed in bold chilli-garlic Manchurian sauce.",
    price: 320,
    rating: 4.2,
    image: "/images/soya-chaap-manchuria.jpg",
    ingredients: ["Soya Chaap", "Manchurian Sauce", "Spring Onion", "Chilli"],
    allergens: ["Soy"],
    prepTime: "18 mins"
  },
  {
    id: "starter-8",
    title: "Baby Corn Manchuria",
    teluguTitle: "బేబీ కార్న్ మంచూరియా",
    category: "STARTERS",
    description: "Tender baby corn fried in crispy batter and tossed in spicy Manchurian sauce.",
    price: 320,
    rating: 4.3,
    image: "/images/baby-corn-manchuria.jpg",
    ingredients: ["Baby Corn", "Soy Sauce", "Garlic", "Green Chilli"],
    allergens: ["Soy", "Gluten"],
    prepTime: "15 mins"
  },
  {
    id: "starter-9",
    title: "Baby Corn Majestic",
    teluguTitle: "బేబీ కార్న్ మెజెస్టిక్",
    category: "STARTERS",
    description: "Baby corn marinated in spiced curd, deep-fried to crispy perfection with curry leaves.",
    price: 310,
    rating: 4.4,
    image: "/images/baby-corn-majestic.jpg",
    isSignature: true,
    ingredients: ["Baby Corn", "Curd Batter", "Curry Leaves", "Red Chilli"],
    allergens: ["Dairy"],
    prepTime: "16 mins"
  },
  {
    id: "starter-10",
    title: "Chilly Paneer",
    teluguTitle: "చిల్లీ పనీర్",
    category: "STARTERS",
    description: "Cottage cheese sautéed with colourful bell peppers, onions, and fiery chilli garlic sauce.",
    price: "310 / 250",
    rating: 4.5,
    image: "/images/chilly-paneer.jpg",
    isPopular: true,
    ingredients: ["Paneer", "Capsicum", "Onion", "Green Chilli", "Soy Sauce"],
    allergens: ["Dairy", "Soy"],
    prepTime: "15 mins"
  },
  {
    id: "starter-11",
    title: "Chilly Baby Corn",
    teluguTitle: "చిల్లీ బేబీ కార్న్",
    category: "STARTERS",
    description: "Stir-fried baby corn with peppers and onions in a spicy Indo-Chinese chilli sauce.",
    price: 320,
    rating: 4.2,
    image: "/images/chilly-baby-corn.jpg",
    ingredients: ["Baby Corn", "Bell Peppers", "Onion", "Chilli Sauce"],
    allergens: ["Soy"],
    prepTime: "15 mins"
  },
  {
    id: "starter-12",
    title: "Mushroom Manchuria",
    teluguTitle: "మష్రూమ్ మంచూరియా",
    category: "STARTERS",
    description: "Whole button mushrooms fried in crispy batter and tossed in a classic Manchurian sauce.",
    price: 320,
    rating: 4.3,
    image: "/images/mushroom-manchuria.jpg",
    ingredients: ["Button Mushrooms", "Manchurian Sauce", "Garlic", "Spring Onion"],
    allergens: ["Soy", "Gluten"],
    prepTime: "15 mins"
  },
  {
    id: "starter-13",
    title: "Chilly Mushroom",
    teluguTitle: "చిల్లీ మష్రూమ్",
    category: "STARTERS",
    description: "Sautéed mushrooms tossed in fiery green chilli and garlic sauce with capsicum and onions.",
    price: 320,
    rating: 4.2,
    image: "/images/chilly-mushroom.jpg",
    ingredients: ["Mushrooms", "Green Chilli", "Garlic", "Capsicum"],
    allergens: ["Soy"],
    prepTime: "15 mins"
  },
  {
    id: "starter-14",
    title: "Crispi Corn",
    teluguTitle: "క్రిస్పీ కార్న్",
    category: "STARTERS",
    description: "Crunchy sweet corn kernels coated in a light crispy batter and tossed with chilli flakes.",
    price: 320,
    rating: 4.4,
    image: "/images/crispy-corn.jpg",
    isPopular: true,
    ingredients: ["Sweet Corn", "Cornflour", "Chilli Flakes", "Lemon"],
    prepTime: "12 mins"
  },
  {
    id: "starter-15",
    title: "Tandoori Paneer Tikka Dry",
    teluguTitle: "తందూరీ పనీర్ టిక్కా",
    category: "STARTERS",
    description: "Succulent paneer cubes marinated in spiced yoghurt and char-grilled in a clay tandoor. (20 min wait)",
    price: 350,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&auto=format&fit=crop&q=80",
    isChefSpecial: true,
    ingredients: ["Paneer", "Yoghurt", "Bell Peppers", "Onions", "Tandoori Masala"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "starter-16",
    title: "Tandoori Soya Chaap",
    teluguTitle: "తందూరీ సోయా చాప్",
    category: "STARTERS",
    description: "Marinated soya chaap grilled to perfection in a traditional clay tandoor. (20 min wait)",
    price: 350,
    rating: 4.5,
    image: "/images/tandoori-soya-chaap.jpg",
    ingredients: ["Soya Chaap", "Yoghurt Marinade", "Spices", "Chaat Masala"],
    allergens: ["Dairy", "Soy"],
    prepTime: "20 mins"
  },

  // ─── SPECIAL STARTERS ────────────────────────────────────────────────────
  {
    id: "spl-starter-1",
    title: "French Fries",
    teluguTitle: "ఫ్రెంచ్ ఫ్రైస్",
    category: "SPL. STARTERS",
    description: "Golden crispy potato fingers seasoned with a special spice mix and served with dips.",
    price: 270,
    rating: 4.3,
    image: "/images/french-fries.jpg",
    ingredients: ["Potatoes", "Salt", "Pepper", "Spice Mix"],
    prepTime: "10 mins"
  },
  {
    id: "spl-starter-2",
    title: "Honey Chilly Potato",
    teluguTitle: "హనీ చిల్లీ పోటేటో",
    category: "SPL. STARTERS",
    description: "Crispy potato fingers tossed in a sweet honey chilli sauce with sesame seeds.",
    price: 350,
    rating: 4.6,
    image: "/images/honey-chilly-potato.jpg",
    isPopular: true,
    ingredients: ["Potato", "Honey", "Chilli Sauce", "Sesame Seeds", "Spring Onion"],
    prepTime: "12 mins"
  },
  {
    id: "spl-starter-3",
    title: "Crispy Baby Corn",
    teluguTitle: "క్రిస్పీ బేబీ కార్న్",
    category: "SPL. STARTERS",
    description: "Baby corn dipped in a seasoned batter, fried until golden crispy and served with sauce.",
    price: 320,
    rating: 4.4,
    image: "/images/crispy-baby-corn.jpg",
    ingredients: ["Baby Corn", "Batter", "Spices"],
    prepTime: "12 mins"
  },
  {
    id: "spl-starter-4",
    title: "Mushroom Butter Pepper",
    teluguTitle: "మష్రూమ్ బటర్ పెప్పర్",
    category: "SPL. STARTERS",
    description: "Sautéed mushrooms in rich butter sauce with freshly cracked black pepper and herbs.",
    price: 320,
    rating: 4.5,
    image: "/images/mushroom-butter-pepper.jpg",
    isSignature: true,
    ingredients: ["Mushrooms", "Butter", "Black Pepper", "Garlic", "Herbs"],
    allergens: ["Dairy"],
    prepTime: "12 mins"
  },
  {
    id: "spl-starter-5",
    title: "Sangrilla Paneer",
    teluguTitle: "సంగ్రిల్లా పనీర్",
    category: "SPL. STARTERS",
    description: "Paneer cubes marinated in a special tangy sauce and grilled with vegetables.",
    price: 320,
    rating: 4.4,
    image: "/images/sangrilla-paneer.jpg",
    ingredients: ["Paneer", "Bell Peppers", "Onion", "Special Sauce"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "spl-starter-6",
    title: "Stick Paneer",
    teluguTitle: "స్టిక్ పనీర్",
    category: "SPL. STARTERS",
    description: "Long paneer sticks coated in spiced batter and fried golden with a crunchy exterior.",
    price: 350,
    rating: 4.5,
    image: "/images/stick-paneer.jpg",
    ingredients: ["Paneer", "Spiced Batter", "Chaat Masala"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "15 mins"
  },
  {
    id: "spl-starter-7",
    title: "Dragon Paneer",
    teluguTitle: "డ్రాగన్ పనీర్",
    category: "SPL. STARTERS",
    description: "Fiery hot paneer in a dragon sauce made with five chillies — for the brave-hearted!",
    price: 350,
    rating: 4.6,
    image: "/images/dragon-paneer.jpg",
    isChefSpecial: true,
    isSignature: true,
    ingredients: ["Paneer", "Dragon Sauce", "Garlic", "Red Chillies"],
    allergens: ["Dairy", "Soy"],
    prepTime: "18 mins"
  },
  {
    id: "spl-starter-8",
    title: "Narmda Paneer",
    teluguTitle: "నర్మదా పనీర్",
    category: "SPL. STARTERS",
    description: "A chef's signature starter — paneer in a rich special sauce with exotic spice blend.",
    price: 350,
    rating: 4.5,
    image: "/images/narmda-paneer.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Special Sauce", "Exotic Spices"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "spl-starter-9",
    title: "Veg. Spring Roll",
    teluguTitle: "వెజ్ స్ప్రింగ్ రోల్",
    category: "SPL. STARTERS",
    description: "Crispy golden rolls filled with stir-fried mixed vegetables and seasoned with soy. (20 min wait)",
    price: 350,
    rating: 4.3,
    image: "/images/veg-spring-roll.jpg",
    ingredients: ["Mixed Vegetables", "Spring Roll Sheets", "Soy Sauce", "Ginger"],
    allergens: ["Gluten", "Soy"],
    prepTime: "20 mins"
  },
  {
    id: "spl-starter-10",
    title: "Veg. Bullet",
    teluguTitle: "వెజ్ బులెట్",
    category: "SPL. STARTERS",
    description: "Stuffed torpedo-shaped veggie rolls — crunchy outside, spicy filling inside. (20 min wait)",
    price: 350,
    rating: 4.4,
    image: "/images/veg-bullet.jpg",
    ingredients: ["Mixed Veggies", "Spiced Filling", "Batter"],
    prepTime: "20 mins"
  },
  {
    id: "spl-starter-11",
    title: "Krishna Spl. Paneer",
    teluguTitle: "కృష్ణ స్పెషల్ పనీర్",
    category: "SPL. STARTERS",
    description: "Our house signature paneer starter — the chef's best-kept secret recipe.",
    price: 350,
    rating: 4.8,
    image: "/images/krishna-spl-paneer.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Special House Spices", "Cream", "Capsicum"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "spl-starter-12",
    title: "Krishna Spl. Veg",
    teluguTitle: "కృష్ణ స్పెషల్ వెజ్",
    category: "SPL. STARTERS",
    description: "A mixed vegetable special starter cooked with our signature house masala.",
    price: 350,
    rating: 4.6,
    image: "/images/krishna-spl-veg.jpg",
    isChefSpecial: true,
    ingredients: ["Mixed Vegetables", "House Masala", "Fresh Herbs"],
    prepTime: "20 mins"
  },

  // ─── 65 SPECIALS ─────────────────────────────────────────────────────────
  {
    id: "65-1",
    title: "Veg. 65",
    teluguTitle: "వెజ్ 65",
    category: "65' KI PASAND",
    description: "Spicy mixed vegetable balls deep-fried and tempered with mustard, curry leaves and chillies.",
    price: 290,
    rating: 4.2,
    image: "/images/veg-65.jpg",
    ingredients: ["Mixed Veggies", "Curry Leaves", "Mustard", "Red Chilli"],
    prepTime: "15 mins"
  },
  {
    id: "65-2",
    title: "Alu 65",
    teluguTitle: "ఆలూ 65",
    category: "65' KI PASAND",
    description: "Crispy fried potato chunks seasoned in a tangy chilli-curd marinade with curry leaves.",
    price: 290,
    rating: 4.1,
    image: "/images/aloo-65.jpg",
    ingredients: ["Potato", "Yoghurt", "Curry Leaves", "Red Chilli"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "65-3",
    title: "Soya Chaap 65",
    teluguTitle: "సోయా చాప్ 65",
    category: "65' KI PASAND",
    description: "Marinated soya chaap fried crispy and tempered with classic 65 spices.",
    price: 350,
    rating: 4.3,
    image: "/images/soya-chaap-65.jpg",
    ingredients: ["Soya Chaap", "Yoghurt", "Curry Leaves", "Spices"],
    allergens: ["Dairy", "Soy"],
    prepTime: "18 mins"
  },
  {
    id: "65-4",
    title: "Gobhi 65",
    teluguTitle: "గోబీ 65",
    category: "65' KI PASAND",
    description: "Crispy cauliflower florets marinated in spiced yoghurt and deep-fried to golden perfection.",
    price: 290,
    rating: 4.2,
    image: "/images/gobi-65.jpg",
    ingredients: ["Cauliflower", "Yoghurt", "Curry Leaves", "Garam Masala"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "65-5",
    title: "Paneer 65",
    teluguTitle: "పనీర్ 65",
    category: "65' KI PASAND",
    description: "Crispy fried cottage cheese chunks tossed in spicy tempering yoghurt sauce and curry leaves.",
    price: 340,
    rating: 4.5,
    image: "/images/paneer-65.jpg",
    isPopular: true,
    ingredients: ["Paneer", "Yoghurt", "Red Chilli Paste", "Curry Leaves", "Mustard Seeds"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "65-6",
    title: "Baby Corn 65",
    teluguTitle: "బేబీ కార్న్ 65",
    category: "65' KI PASAND",
    description: "Tender baby corn marinated in spiced curd and fried with classic 65 tempering.",
    price: 340,
    rating: 4.3,
    image: "/images/baby-corn-65.jpg",
    ingredients: ["Baby Corn", "Yoghurt", "Curry Leaves", "Chilli"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "65-7",
    title: "Mushroom 65",
    teluguTitle: "మష్రూమ్ 65",
    category: "65' KI PASAND",
    description: "Fresh button mushrooms coated in spicy batter, fried and tempered with mustard and chillies.",
    price: 340,
    rating: 4.3,
    image: "/images/mushroom-65.jpg",
    ingredients: ["Button Mushrooms", "Curry Leaves", "Yoghurt Sauce", "Spices"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },

  // ─── CHINESE ──────────────────────────────────────────────────────────────
  {
    id: "chinese-1",
    title: "Veg. Noodles",
    teluguTitle: "వెజ్ నూడిల్స్",
    category: "CHINESE",
    description: "Stir-fried hakka noodles with fresh vegetables in a classic Indo-Chinese sauce.",
    price: 240,
    rating: 4.1,
    image: "/images/veg-noodles.jpg",
    ingredients: ["Noodles", "Mixed Veggies", "Soy Sauce", "Garlic"],
    allergens: ["Gluten", "Soy"],
    prepTime: "12 mins"
  },
  {
    id: "chinese-2",
    title: "Fried Noodles",
    teluguTitle: "ఫ్రైడ్ నూడిల్స్",
    category: "CHINESE",
    description: "Crispy pan-fried noodles with colourful vegetables in a savory sauce.",
    price: 250,
    rating: 4.2,
    image: "/images/fried-noodles.jpg",
    ingredients: ["Noodles", "Vegetables", "Soy Sauce", "Oil"],
    allergens: ["Gluten", "Soy"],
    prepTime: "14 mins"
  },
  {
    id: "chinese-3",
    title: "American Chop Suey",
    teluguTitle: "అమెరికన్ చాప్ సుయే",
    category: "CHINESE",
    description: "Crispy noodles topped with mixed vegetable stir-fry in tangy sweet & sour sauce.",
    price: 320,
    rating: 4.4,
    image: "/images/american-chop-suey.jpg",
    isPopular: true,
    ingredients: ["Crispy Noodles", "Mixed Veggies", "Sweet Sour Sauce", "Tomato Ketchup"],
    allergens: ["Gluten", "Soy"],
    prepTime: "15 mins"
  },
  {
    id: "chinese-4",
    title: "Schezwan Noodles",
    teluguTitle: "షెజ్వాన్ నూడిల్స్",
    category: "CHINESE",
    description: "Spicy Schezwan noodles stir-fried with veggies and aromatic Schezwan sauce.",
    price: 270,
    rating: 4.3,
    image: "/images/schezwan-noodles.jpg",
    ingredients: ["Noodles", "Schezwan Sauce", "Vegetables", "Garlic"],
    allergens: ["Gluten", "Soy"],
    prepTime: "14 mins"
  },
  {
    id: "chinese-5",
    title: "Hakka Noodles",
    teluguTitle: "హక్కా నూడిల్స్",
    category: "CHINESE",
    description: "Classic hakka-style stir-fried noodles with crisp vegetables and light seasoning.",
    price: 290,
    rating: 4.2,
    image: "/images/hakka-noodles.jpg",
    ingredients: ["Hakka Noodles", "Cabbage", "Carrot", "Spring Onion", "Soy Sauce"],
    allergens: ["Gluten", "Soy"],
    prepTime: "12 mins"
  },

  // ─── SALAD ────────────────────────────────────────────────────────────────
  {
    id: "salad-1",
    title: "Masala Chatpat Salad",
    teluguTitle: "మసాలా చట్పట సలాడ్",
    category: "SALAD",
    description: "Fresh seasonal vegetables tossed with chaat masala, lemon and green chilli for a tangy punch.",
    price: 120,
    rating: 4.1,
    image: "/images/masala-chatpat-salad.jpg",
    ingredients: ["Cucumber", "Tomato", "Onion", "Chaat Masala", "Lemon"],
    prepTime: "5 mins"
  },
  {
    id: "salad-2",
    title: "Tomato Onion Salad",
    teluguTitle: "టొమాటో ఉల్లి సలాడ్",
    category: "SALAD",
    description: "Simple and refreshing sliced tomatoes and onions with salt, pepper and lemon juice.",
    price: 120,
    rating: 4.0,
    image: "/images/tomato-onion-salad.png",
    ingredients: ["Tomato", "Onion", "Lemon", "Salt", "Pepper"],
    prepTime: "5 mins"
  },
  {
    id: "salad-3",
    title: "Green Salad",
    teluguTitle: "గ్రీన్ సలాడ్",
    category: "SALAD",
    description: "Fresh green leafy salad with cucumber, capsicum and light dressing.",
    price: 140,
    rating: 4.0,
    image: "/images/green-salad.jpg",
    ingredients: ["Lettuce", "Cucumber", "Capsicum", "Olive Oil"],
    prepTime: "5 mins"
  },

  // ─── DAL BAHAR ────────────────────────────────────────────────────────────
  {
    id: "dal-1",
    title: "Dal Makhani",
    teluguTitle: "దాల్ మఖని",
    category: "DAL BAHAR",
    description: "Slow-cooked black lentils in buttery tomato gravy with cream — a North Indian classic.",
    price: 270,
    rating: 4.6,
    image: "/images/dal-makhani.jpg",
    isPopular: true,
    ingredients: ["Black Urad Dal", "Rajma", "Butter", "Cream", "Tomatoes"],
    allergens: ["Dairy"],
    prepTime: "25 mins"
  },
  {
    id: "dal-2",
    title: "Dal Fry",
    teluguTitle: "దాల్ ఫ్రై",
    category: "DAL BAHAR",
    description: "Yellow lentils tempered with ghee, cumin, garlic and red chilli for a simple hearty dal.",
    price: "240 / 190",
    rating: 4.3,
    image: "/images/dal-fry.jpg",
    ingredients: ["Yellow Dal", "Ghee", "Cumin", "Garlic", "Red Chilli"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "dal-3",
    title: "Dal Pan Methi Wala",
    teluguTitle: "దాల్ పాన్ మెంతి వాలా",
    category: "DAL BAHAR",
    description: "Lentils cooked with fresh fenugreek leaves and tempered with aromatic spices.",
    price: 250,
    rating: 4.2,
    image: "/images/dal-pan-methi.jpg",
    ingredients: ["Toor Dal", "Fenugreek Leaves", "Tomato", "Spices"],
    prepTime: "20 mins"
  },
  {
    id: "dal-4",
    title: "Dal Palak",
    teluguTitle: "దాల్ పాలక్",
    category: "DAL BAHAR",
    description: "Nutritious lentils cooked with fresh spinach and tempered with garlic and mustard.",
    price: 220,
    rating: 4.2,
    image: "/images/dal-palak.png",
    ingredients: ["Toor Dal", "Spinach", "Garlic", "Mustard Seeds"],
    prepTime: "20 mins"
  },
  {
    id: "dal-5",
    title: "Dal Tadka",
    teluguTitle: "దాల్ తడ్కా",
    category: "DAL BAHAR",
    description: "Classic yellow dal with a sizzling ghee tempering of cumin, garlic and dried red chilli.",
    price: 270,
    rating: 4.4,
    image: "/images/dal-tadka.jpg",
    ingredients: ["Yellow Dal", "Ghee", "Cumin", "Asafoetida", "Red Chilli"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "dal-6",
    title: "Dal Butter",
    teluguTitle: "దాల్ బటర్",
    category: "DAL BAHAR",
    description: "Creamy yellow dal enriched with a generous dollop of fresh butter.",
    price: 250,
    rating: 4.3,
    image: "/images/dal-butter.jpg",
    ingredients: ["Yellow Dal", "Butter", "Cumin", "Onion", "Tomato"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },

  // ─── KOFTA CURRIES ────────────────────────────────────────────────────────
  {
    id: "kofta-1",
    title: "Veg. Kofta",
    teluguTitle: "వెజ్ కోఫ్తా",
    category: "KOFTA KI CURRIES",
    description: "Soft mixed vegetable dumplings simmered in a rich and mildly spiced onion-tomato gravy.",
    price: 310,
    rating: 4.3,
    image: "/images/veg-kofta.jpg",
    ingredients: ["Mixed Vegetables", "Cashew Paste", "Tomato Gravy", "Cream"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "20 mins"
  },
  {
    id: "kofta-2",
    title: "Malai Kofta (Sweet)",
    teluguTitle: "మలాయ్ కోఫ్తా",
    category: "KOFTA KI CURRIES",
    description: "Delicate paneer and khoya dumplings in a luxurious, mildly sweet cashew-cream gravy.",
    price: 310,
    rating: 4.6,
    image: "/images/malai-kofta.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Khoya", "Cashew Cream", "Cardamom", "Rose Water"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "22 mins"
  },
  {
    id: "kofta-3",
    title: "Paneer Kofta",
    teluguTitle: "పనీర్ కోఫ్తా",
    category: "KOFTA KI CURRIES",
    description: "Soft paneer dumplings cooked in a spiced tomato-onion gravy with a hint of cream.",
    price: 320,
    rating: 4.4,
    image: "/images/paneer-kofta.jpg",
    ingredients: ["Paneer", "Onion Gravy", "Spices", "Cream"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "kofta-4",
    title: "Punjabi Kofta",
    teluguTitle: "పంజాబీ కోఫ్తా",
    category: "KOFTA KI CURRIES",
    description: "Hearty Punjabi-style veggie koftas in a robust, spice-forward tomato gravy.",
    price: 320,
    rating: 4.3,
    image: "/images/punjabi-kofta.png",
    ingredients: ["Mixed Veggies", "Tomato Gravy", "Dhaba Spices"],
    prepTime: "20 mins"
  },
  {
    id: "kofta-5",
    title: "Rani Kofta",
    teluguTitle: "రాణీ కోఫ్తా",
    category: "KOFTA KI CURRIES",
    description: "Chef's royal kofta in a rich golden gravy with mild sweetness from cashews and cream.",
    price: 320,
    rating: 4.5,
    image: "/images/rani-kofta.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Cashews", "Cream", "Royal Spices"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "22 mins"
  },
  {
    id: "kofta-6",
    title: "Bulbul Kofta",
    teluguTitle: "బుల్బుల్ కోఫ్తా",
    category: "KOFTA KI CURRIES",
    description: "Specialty kofta made with a unique mix of veggies and cottage cheese in aromatic gravy.",
    price: 350,
    rating: 4.5,
    image: "/images/bulbul-kofta.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Mixed Veggies", "Aromatic Gravy"],
    allergens: ["Dairy"],
    prepTime: "22 mins"
  },

  // ─── CURRIES (Alu / Gobhi / etc.) ─────────────────────────────────────────
  {
    id: "curry-alu-1",
    title: "Alu Jeera Dry",
    teluguTitle: "ఆలూ జీరా డ్రై",
    category: "CURRIES",
    description: "Baby potatoes sautéed in fragrant cumin, fresh coriander and dry spices — a simple classic.",
    price: 290,
    rating: 4.2,
    image: "/images/aloo-jeera-dry.jpg",
    ingredients: ["Baby Potatoes", "Cumin", "Coriander", "Dry Spices"],
    prepTime: "15 mins"
  },
  {
    id: "curry-alu-2",
    title: "Alu Gobhi Masala",
    teluguTitle: "ఆలూ గోబీ మసాలా",
    category: "CURRIES",
    description: "Potatoes and cauliflower cooked in a dry masala with tomatoes, ginger and aromatic spices.",
    price: 290,
    rating: 4.3,
    image: "/images/aloo-gobhi-masala.png",
    ingredients: ["Potato", "Cauliflower", "Tomato", "Masala Spices"],
    prepTime: "18 mins"
  },
  {
    id: "curry-alu-3",
    title: "Alu Palak",
    teluguTitle: "ఆలూ పాలక్",
    category: "CURRIES",
    description: "Tender potatoes cooked in a fresh spinach purée with garlic and warming spices.",
    price: 280,
    rating: 4.1,
    image: "/images/aloo-palak.jpg",
    ingredients: ["Potato", "Spinach", "Garlic", "Cream"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "curry-alu-4",
    title: "Alu Mutter",
    teluguTitle: "ఆలూ మటర్",
    category: "CURRIES",
    description: "Classic Punjabi potato and green peas curry in a tomato-onion gravy.",
    price: 280,
    rating: 4.2,
    image: "/images/aloo-mutter.jpg",
    ingredients: ["Potatoes", "Green Peas", "Tomato Gravy", "Spices"],
    prepTime: "15 mins"
  },
  {
    id: "curry-corn-1",
    title: "Baby Corn Masala",
    teluguTitle: "బేబీ కార్న్ మసాలా",
    category: "CURRIES",
    description: "Tender baby corn cooked in a spicy tomato-onion masala gravy.",
    price: 290,
    rating: 4.2,
    image: "/images/baby-corn-masala.png",
    ingredients: ["Baby Corn", "Tomato Gravy", "Onion", "Spices"],
    prepTime: "16 mins"
  },
  {
    id: "curry-mush-1",
    title: "Butter Mushroom Masala",
    teluguTitle: "బటర్ మష్రూమ్ మసాలా",
    category: "CURRIES",
    description: "Juicy button mushrooms simmered in a rich, buttery tomato gravy with aromatic spices.",
    price: 310,
    rating: 4.4,
    image: "/images/butter-mushroom-masala.png",
    ingredients: ["Mushrooms", "Butter", "Tomato Gravy", "Kasturi Methi"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "curry-corn-2",
    title: "Corn Palak",
    teluguTitle: "కార్న్ పాలక్",
    category: "CURRIES",
    description: "Sweet corn kernels cooked in a velvety spinach gravy seasoned with mild spices.",
    price: 280,
    rating: 4.1,
    image: "/images/corn-palak.png",
    ingredients: ["Corn", "Spinach", "Ginger", "Garlic", "Cream"],
    allergens: ["Dairy"],
    prepTime: "16 mins"
  },
  {
    id: "curry-cap-1",
    title: "Capsicum Masala",
    teluguTitle: "కాప్సికమ్ మసాలా",
    category: "CURRIES",
    description: "Colourful bell peppers cooked in a rich spiced tomato-onion gravy.",
    price: 280,
    rating: 4.1,
    image: "/images/capsicum-masala.png",
    ingredients: ["Capsicum", "Tomato", "Onion", "Masala Spices"],
    prepTime: "16 mins"
  },
  {
    id: "curry-chana-1",
    title: "Chana Masala",
    teluguTitle: "చనా మసాలా",
    category: "CURRIES",
    description: "Soft chickpeas cooked in a deeply flavorful tomato-onion gravy with roasted cumin.",
    price: 280,
    rating: 4.3,
    image: "/images/chana-masala.jpg",
    ingredients: ["Kabuli Chana", "Tomato Gravy", "Garam Masala", "Ginger", "Amchoor"],
    prepTime: "15 mins"
  },
  {
    id: "curry-dam-1",
    title: "Dam-Ka-Alu",
    teluguTitle: "దమ్ కా ఆలూ",
    category: "CURRIES",
    description: "Baby potatoes slow-cooked in a dum style spiced gravy — restaurant favourite.",
    price: 280,
    rating: 4.3,
    image: "/images/dum-aloo.jpg",
    ingredients: ["Baby Potatoes", "Yoghurt", "Onion Gravy", "Dum Spices"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "curry-dum-1",
    title: "Dum Alu Nawabi",
    teluguTitle: "దమ్ ఆలూ నవాబీ",
    category: "CURRIES",
    description: "Whole small potatoes cooked Nawabi style in a royal aromatic gravy with rose water.",
    price: 290,
    rating: 4.4,
    image: "/images/dum-aloo-nawabi.png",
    ingredients: ["Baby Potatoes", "Cream", "Nuts", "Rose Water", "Aromatic Spices"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "22 mins"
  },
  {
    id: "curry-gp-1",
    title: "Green Peas Masala",
    teluguTitle: "గ్రీన్ పీస్ మసాలా",
    category: "CURRIES",
    description: "Fresh green peas in a spiced tomato-onion gravy with ginger and aromatic spices.",
    price: 280,
    rating: 4.1,
    image: "/images/green-peas-masala.jpg",
    ingredients: ["Green Peas", "Tomato", "Onion", "Masala"],
    prepTime: "15 mins"
  },
  {
    id: "curry-gp-2",
    title: "Ginger Paneer",
    teluguTitle: "జింజర్ పనీర్",
    category: "CURRIES",
    description: "Paneer cubes simmered in a zingy fresh ginger-forward tomato gravy.",
    price: 320,
    rating: 4.3,
    image: "/images/ginger-paneer.jpg",
    ingredients: ["Paneer", "Fresh Ginger", "Tomato", "Spices"],
    allergens: ["Dairy"],
    prepTime: "16 mins"
  },
  {
    id: "curry-hara-1",
    title: "Hara Bhara Masala",
    teluguTitle: "హరా భరా మసాలా",
    category: "CURRIES",
    description: "A lush green curry with spinach, peas and fresh herbs in a vibrant green gravy.",
    price: 320,
    rating: 4.4,
    image: "/images/hara-bhara-masala.jpg",
    ingredients: ["Spinach", "Peas", "Mint", "Coriander", "Spices"],
    prepTime: "18 mins"
  },
  {
    id: "curry-handi-1",
    title: "Handi Paneer",
    teluguTitle: "హండి పనీర్",
    category: "CURRIES",
    description: "Paneer cooked slow in a traditional clay handi with rich onion-tomato masala.",
    price: 310,
    rating: 4.5,
    image: "/images/handi-paneer.jpg",
    isPopular: true,
    ingredients: ["Paneer", "Clay Pot Gravy", "Kasuri Methi", "Cream"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "curry-kadai-v",
    title: "Kadai Veg.",
    teluguTitle: "కడాయ్ వెజ్",
    category: "CURRIES",
    description: "Mixed vegetables tossed in a fiery kadai masala with bell peppers and onions.",
    price: 310,
    rating: 4.2,
    image: "/images/kadai-veg.jpg",
    ingredients: ["Mixed Vegetables", "Kadai Masala", "Capsicum", "Onion"],
    prepTime: "18 mins"
  },
  {
    id: "curry-kadai-p",
    title: "Kadai Paneer",
    teluguTitle: "కడాయ్ పనీర్",
    category: "CURRIES",
    description: "Paneer and capsicum simmered in a robust kadai masala with fresh tomatoes.",
    price: 310,
    rating: 4.5,
    image: "/images/kadai-paneer.jpg",
    isPopular: true,
    ingredients: ["Paneer", "Capsicum", "Tomato", "Kadai Masala"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "curry-kaju-1",
    title: "Kaju Butter Masala",
    teluguTitle: "కాజు బటర్ మసాలా",
    category: "CURRIES",
    description: "Whole cashews in a buttery, velvety tomato gravy — rich, mildly sweet, irresistible.",
    price: 320,
    rating: 4.6,
    image: "/images/kaju-butter-masala.jpg",
    isChefSpecial: true,
    ingredients: ["Cashew Nuts", "Butter", "Tomato Puree", "Cream", "Kasuri Methi"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "20 mins"
  },
  {
    id: "curry-kaju-2",
    title: "Kaju Paneer",
    teluguTitle: "కాజు పనీర్",
    category: "CURRIES",
    description: "Cashews and paneer combined in a rich cream-tomato gravy — double indulgence.",
    price: "320 / 250",
    rating: 4.5,
    image: "/images/kaju-paneer.jpg",
    ingredients: ["Paneer", "Cashews", "Tomato Gravy", "Cream"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "20 mins"
  },
  {
    id: "curry-kadai-mush",
    title: "Kadai Mushroom",
    teluguTitle: "కడాయ్ మష్రూమ్",
    category: "CURRIES",
    description: "Juicy mushrooms cooked in a spicy kadai masala with onions and capsicum.",
    price: 310,
    rating: 4.3,
    image: "/images/kadai-mushroom.jpg",
    ingredients: ["Mushrooms", "Kadai Masala", "Capsicum", "Tomato"],
    prepTime: "18 mins"
  },
  {
    id: "curry-lacha",
    title: "Lacha Lacha Paneer",
    teluguTitle: "లచ్చా లచ్చా పనీర్",
    category: "CURRIES",
    description: "Shredded paneer cooked in a uniquely layered onion-tomato gravy — rich and flavourful.",
    price: 320,
    rating: 4.5,
    image: "/images/lachha-paneer.jpg",
    isChefSpecial: true,
    ingredients: ["Shredded Paneer", "Onion Gravy", "Cream", "Special Spices"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "curry-mutter-palak",
    title: "Mutter Palak",
    teluguTitle: "మటర్ పాలక్",
    category: "CURRIES",
    description: "Green peas and fresh spinach cooked together in a smooth, lightly spiced gravy.",
    price: 300,
    rating: 4.2,
    image: "/images/mutter-palak.jpg",
    ingredients: ["Green Peas", "Spinach", "Garlic", "Ginger"],
    prepTime: "15 mins"
  },
  {
    id: "curry-mutter-paneer",
    title: "Mutter Paneer",
    teluguTitle: "మటర్ పనీర్",
    category: "CURRIES",
    description: "The beloved classic — green peas and paneer in a comforting tomato-onion gravy.",
    price: 300,
    rating: 4.5,
    image: "/images/mutter-paneer.jpg",
    isPopular: true,
    ingredients: ["Paneer", "Green Peas", "Tomato Gravy", "Garam Masala"],
    allergens: ["Dairy"],
    prepTime: "16 mins"
  },

  // ─── VEG CURRIES (Main menu section) ─────────────────────────────────────
  {
    id: "main-curry-1",
    title: "Mix Vegetable",
    teluguTitle: "మిక్స్ వెజిటబుల్",
    category: "CURRIES",
    description: "Seasonal mixed vegetables simmered in a North Indian style spiced gravy.",
    price: "290 / 190",
    rating: 4.1,
    image: "/images/mix-vegetable.jpg",
    ingredients: ["Seasonal Veggies", "Tomato", "Onion", "Masala"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-2",
    title: "Marwadi Veg.",
    teluguTitle: "మార్వాడీ వెజ్",
    category: "CURRIES",
    description: "A hearty Rajasthani-style vegetable curry with dried spices and traditional flavours.",
    price: 320,
    rating: 4.3,
    image: "/images/marwadi-veg.jpg",
    ingredients: ["Mixed Veggies", "Rajasthani Spices", "Ghee"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-3",
    title: "Mutter Mushroom Masala",
    teluguTitle: "మటర్ మష్రూమ్ మసాలా",
    category: "CURRIES",
    description: "Green peas and mushrooms in a robust, spicy masala gravy.",
    price: 320,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1569460555907-8ffc8a8bd9cf?w=600&auto=format&fit=crop&q=80",
    ingredients: ["Mushrooms", "Green Peas", "Tomato Gravy", "Masala"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-4",
    title: "Mushroom Masala",
    teluguTitle: "మష్రూమ్ మసాలా",
    category: "CURRIES",
    description: "Fresh mushrooms cooked in a spiced onion-tomato gravy with aromatic spices.",
    price: 340,
    rating: 4.4,
    image: "/images/mushroom-masala.jpg",
    ingredients: ["Mushrooms", "Onion Gravy", "Spices", "Herbs"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-5",
    title: "Mushroom Paneer",
    teluguTitle: "మష్రూమ్ పనీర్",
    category: "CURRIES",
    description: "Mushrooms and paneer cubes cooked together in a rich masala gravy.",
    price: 340,
    rating: 4.4,
    image: "/images/mushroom-paneer.jpg",
    ingredients: ["Mushrooms", "Paneer", "Tomato Gravy", "Spices"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-6",
    title: "Methi Chamman",
    teluguTitle: "మేతీ చమ్మన్",
    category: "CURRIES",
    description: "Fresh fenugreek leaves cooked with paneer in a mildly spiced cream gravy.",
    price: 280,
    rating: 4.3,
    image: "/images/methi-chaman.jpg",
    ingredients: ["Fenugreek Leaves", "Paneer", "Cream", "Spices"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-7",
    title: "Plain Palak",
    teluguTitle: "పాలక్",
    category: "CURRIES",
    description: "Simple and healthy puréed spinach curry with mild spices and a touch of cream.",
    price: 280,
    rating: 4.1,
    image: "/images/plain-palak.jpg",
    ingredients: ["Spinach", "Ginger", "Garlic", "Cream"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "main-curry-8",
    title: "Punjabi Channa Masala",
    teluguTitle: "పంజాబీ చన్నా మసాలా",
    category: "CURRIES",
    description: "Bold and rustic Punjabi-style chole with whole spices and a smoky tomato base.",
    price: 320,
    rating: 4.5,
    image: "/images/punjabi-channa-masala.jpg",
    isPopular: true,
    ingredients: ["Chickpeas", "Whole Spices", "Tomato", "Anardana"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-9",
    title: "Paneer Butter Masala",
    teluguTitle: "పనీర్ బటర్ మసాలా",
    category: "CURRIES",
    description: "Soft paneer cubes in a silky, buttery tomato-cream sauce — a perennial favourite.",
    price: "310 / 210",
    rating: 4.7,
    image: "/images/paneer-butter-masala.jpg",
    isPopular: true,
    ingredients: ["Paneer", "Butter", "Tomato Purée", "Cream", "Kasuri Methi"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-10",
    title: "Paneer Kheema Masala",
    teluguTitle: "పనీర్ కీమా మసాలా",
    category: "CURRIES",
    description: "Finely crumbled paneer cooked like a spiced kheema in rich tomato-onion masala.",
    price: 310,
    rating: 4.4,
    image: "/images/paneer-kheema-masala.jpg",
    ingredients: ["Crumbled Paneer", "Onion", "Tomato", "Peas", "Spices"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-11",
    title: "Palak Paneer",
    teluguTitle: "పాలక్ పనీర్",
    category: "CURRIES",
    description: "Paneer cubes in a smooth, spiced spinach gravy — a perennial healthy favourite.",
    price: 300,
    rating: 4.6,
    image: "/images/palak-paneer.jpg",
    isPopular: true,
    ingredients: ["Spinach", "Paneer", "Cream", "Garam Masala"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-12",
    title: "Paneer Chatpata",
    teluguTitle: "పనీర్ చటపటా",
    category: "CURRIES",
    description: "Cottage cheese in a tangy chatpata masala gravy with a kick of spice and sour.",
    price: "320 / 220",
    rating: 4.4,
    image: "/images/paneer-chatpata.jpg",
    ingredients: ["Paneer", "Chaat Masala", "Tomato", "Lemon"],
    allergens: ["Dairy"],
    prepTime: "16 mins"
  },
  {
    id: "main-curry-13",
    title: "Paneer Makhan Wala",
    teluguTitle: "పనీర్ మఖన్ వాలా",
    category: "CURRIES",
    description: "Paneer in a silky makhan (butter) sauce, similar to butter masala but richer.",
    price: 310,
    rating: 4.6,
    image: "/images/paneer-makhani.jpg",
    ingredients: ["Paneer", "Makhan", "Cream", "Tomato"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-14",
    title: "Paneer Do Pyazza",
    teluguTitle: "పనీర్ దో ప్యాజ్జా",
    category: "CURRIES",
    description: "Paneer cooked with double the onions — caramelised and raw — in a spiced masala.",
    price: 320,
    rating: 4.4,
    image: "/images/paneer-do-pyaza.jpg",
    ingredients: ["Paneer", "Double Onion", "Tomato", "Masala"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-15",
    title: "Paneer Bhurji",
    teluguTitle: "పనీర్ భుర్జీ",
    category: "CURRIES",
    description: "Scrambled cottage cheese sautéed with onions, tomatoes, capsicum and spices.",
    price: 310,
    rating: 4.3,
    image: "/images/paneer-bhurji.jpg",
    ingredients: ["Paneer", "Onion", "Tomato", "Capsicum", "Spices"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "main-curry-16",
    title: "Paneer Patiala (Sweet)",
    teluguTitle: "పనీర్ పాటియాలా",
    category: "CURRIES",
    description: "Royal Patiala-style paneer in a mildly sweet, rich saffron-tinged gravy.",
    price: 320,
    rating: 4.4,
    image: "/images/paneer-patiala.jpg",
    ingredients: ["Paneer", "Saffron", "Cream", "Sweet Spices"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-17",
    title: "Paneer Tikka Masala",
    teluguTitle: "పనీర్ టిక్కా మసాలా",
    category: "CURRIES",
    description: "Grilled paneer tikka pieces in a smoky, spiced tomato-cream masala gravy.",
    price: 320,
    rating: 4.7,
    image: "/images/paneer-tikka-masala.jpg",
    isChefSpecial: true,
    ingredients: ["Tandoori Paneer", "Tikka Masala", "Cream", "Onion"],
    allergens: ["Dairy"],
    prepTime: "22 mins"
  },
  {
    id: "main-curry-18",
    title: "Tadka Paneer",
    teluguTitle: "తడ్కా పనీర్",
    category: "CURRIES",
    description: "Paneer in a simple, rustic tadka of ghee, cumin, and spices — pure dhaba style.",
    price: 320,
    rating: 4.3,
    image: "/images/tadka-paneer.jpg",
    ingredients: ["Paneer", "Ghee Tadka", "Cumin", "Onion-Tomato"],
    allergens: ["Dairy"],
    prepTime: "16 mins"
  },
  {
    id: "main-curry-19",
    title: "Tadka Mushroom",
    teluguTitle: "తడ్కా మష్రూమ్",
    category: "CURRIES",
    description: "Fresh mushrooms in a ghee tadka gravy with cumin, onions and tomatoes.",
    price: 320,
    rating: 4.3,
    image: "/images/tadka-mushroom.jpg",
    ingredients: ["Mushrooms", "Ghee Tadka", "Cumin", "Onion-Tomato"],
    allergens: ["Dairy"],
    prepTime: "16 mins"
  },
  {
    id: "main-curry-20",
    title: "Stuffed Capsicum Masala",
    teluguTitle: "స్టఫ్డ్ కాప్సికమ్ మసాలా",
    category: "CURRIES",
    description: "Bell peppers stuffed with spiced paneer/veggie filling and simmered in rich masala.",
    price: 310,
    rating: 4.4,
    image: "/images/stuffed-capsicum-masala.jpg",
    ingredients: ["Capsicum", "Paneer Filling", "Masala Gravy"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-21",
    title: "Stuffed Tomato Masala",
    teluguTitle: "స్టఫ్డ్ టొమాటో మసాలా",
    category: "CURRIES",
    description: "Whole tomatoes stuffed with paneer masala and cooked in a tangy tomato gravy.",
    price: 310,
    rating: 4.3,
    image: "/images/stuffed-tomato-masala.jpg",
    ingredients: ["Tomato", "Paneer Filling", "Masala Gravy"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-22",
    title: "Spl. Punjabi Gobhi Masala",
    teluguTitle: "స్పెషల్ పంజాబీ గోబీ మసాలా",
    category: "CURRIES",
    description: "Cauliflower in a special Punjabi dhaba masala — bold, hearty and deeply spiced.",
    price: 310,
    rating: 4.3,
    image: "/images/punjabi-gobhi-masala.jpg",
    ingredients: ["Cauliflower", "Punjabi Masala", "Onion-Tomato", "Ghee"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-23",
    title: "Shahi Paneer (Sweet)",
    teluguTitle: "షాహీ పనీర్",
    category: "CURRIES",
    description: "Paneer in a Mughal-inspired royal gravy with cashews, cream and cardamom — mildly sweet.",
    price: 320,
    rating: 4.6,
    image: "/images/shahi-paneer.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Cashew Cream", "Cardamom", "Rose Water"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-24",
    title: "Schezwan Handi Paneer",
    teluguTitle: "షెజ్వాన్ హండి పనీర్",
    category: "CURRIES",
    description: "Paneer cooked in a handi with fiery Schezwan sauce and Indo-Chinese spices.",
    price: 320,
    rating: 4.5,
    image: "/images/schezwan-handi-paneer.jpg",
    ingredients: ["Paneer", "Schezwan Sauce", "Handi Gravy"],
    allergens: ["Dairy", "Soy"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-25",
    title: "Soya Chaap Paneer",
    teluguTitle: "సోయా చాప్ పనీర్",
    category: "CURRIES",
    description: "Soya chaap and paneer cooked together in a spiced North Indian masala gravy.",
    price: 320,
    rating: 4.3,
    image: "/images/soya-chaap-paneer.jpg",
    ingredients: ["Soya Chaap", "Paneer", "Masala Gravy"],
    allergens: ["Dairy", "Soy"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-26",
    title: "Tomato Chatni",
    teluguTitle: "టొమాటో చట్నీ",
    category: "CURRIES",
    description: "Tangy and spicy fresh tomato chutney-style curry — a unique dhaba favourite.",
    price: 280,
    rating: 4.0,
    image: "/images/tomato-chutney.jpg",
    ingredients: ["Fresh Tomatoes", "Spices", "Garlic", "Ginger"],
    prepTime: "12 mins"
  },
  {
    id: "main-curry-27",
    title: "Tomato Curry",
    teluguTitle: "టొమాటో కర్రీ",
    category: "CURRIES",
    description: "Simple and comforting tomato-based curry with a rich onion base and mild spicing.",
    price: 280,
    rating: 4.1,
    image: "/images/tomato-curry.jpg",
    ingredients: ["Tomatoes", "Onion", "Spices", "Coriander"],
    prepTime: "15 mins"
  },
  {
    id: "main-curry-28",
    title: "Veg. Korma",
    teluguTitle: "వెజ్ కోర్మా",
    category: "CURRIES",
    description: "Seasonal vegetables in a mildly spiced, cashew-yoghurt korma gravy — royal and fragrant.",
    price: 290,
    rating: 4.3,
    image: "/images/veg-korma.jpg",
    ingredients: ["Mixed Vegetables", "Cashew Paste", "Yoghurt", "Mild Spices"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-29",
    title: "Veg. Keema Masala",
    teluguTitle: "వెజ్ కీమా మసాలా",
    category: "CURRIES",
    description: "Minced vegetable medley cooked in a spicy onion-tomato masala, dhaba style.",
    price: 290,
    rating: 4.2,
    image: "/images/veg-kheema-masala.jpg",
    ingredients: ["Minced Vegetables", "Peas", "Masala", "Coriander"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-30",
    title: "Veg. Garlic",
    teluguTitle: "వెజ్ గార్లిక్",
    category: "CURRIES",
    description: "Mixed vegetables cooked in a bold, garlic-forward gravy with aromatic spices.",
    price: 290,
    rating: 4.1,
    image: "/images/veg-garlic.jpg",
    ingredients: ["Mixed Vegetables", "Roasted Garlic", "Tomato", "Spices"],
    prepTime: "16 mins"
  },
  {
    id: "main-curry-31",
    title: "Veg. Do-Pyazza",
    teluguTitle: "వెజ్ దో ప్యాజ్జా",
    category: "CURRIES",
    description: "Mixed vegetables cooked with twice the onions for a deeply caramelised, rich flavour.",
    price: 290,
    rating: 4.2,
    image: "/images/veg-do-pyaza.jpg",
    ingredients: ["Mixed Vegetables", "Double Onion", "Tomato", "Spices"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-32",
    title: "Veg. Kolapuri",
    teluguTitle: "వెజ్ కొల్హాపురి",
    category: "CURRIES",
    description: "Fiery and bold vegetables in a Kolhapuri-style gravy packed with dry coconut and chillies.",
    price: 310,
    rating: 4.4,
    image: "/images/veg-kolhapuri.jpg",
    ingredients: ["Mixed Vegetables", "Dry Coconut", "Kolhapuri Masala", "Red Chilli"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-33",
    title: "Veg. Jaipuri",
    teluguTitle: "వెజ్ జైపురీ",
    category: "CURRIES",
    description: "Rajasthani-style vegetable curry with dried spices, coriander and Jaipur masala.",
    price: 320,
    rating: 4.3,
    image: "/images/veg-jaipuri.jpg",
    ingredients: ["Mixed Vegetables", "Jaipur Masala", "Dried Spices", "Yoghurt"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "main-curry-34",
    title: "Veg. Punjabi",
    teluguTitle: "వెజ్ పంజాబీ",
    category: "CURRIES",
    description: "A hearty Punjabi dhaba-style mixed vegetable curry with whole spices.",
    price: 320,
    rating: 4.3,
    image: "/images/veg-punjabi.jpg",
    ingredients: ["Mixed Vegetables", "Punjabi Masala", "Onion-Tomato", "Ghee"],
    allergens: ["Dairy"],
    prepTime: "18 mins"
  },
  {
    id: "main-curry-35",
    title: "Veg. Chatpata",
    teluguTitle: "వెజ్ చట్పట",
    category: "CURRIES",
    description: "Chatpata mixed vegetable curry with a tangy, spicy twist of chaat masala.",
    price: 320,
    rating: 4.2,
    image: "/images/veg-chatpata.jpg",
    ingredients: ["Mixed Vegetables", "Chaat Masala", "Lemon", "Spices"],
    prepTime: "16 mins"
  },
  {
    id: "main-curry-36",
    title: "Veg. Navratan Kurma (Sweet)",
    teluguTitle: "వెజ్ నవరతన్ కోర్మా",
    category: "CURRIES",
    description: "Nine treasures — vegetables, fruits and nuts in a mildly sweet royal cream gravy.",
    price: 320,
    rating: 4.5,
    image: "/images/veg-navratan-kurma.jpg",
    isChefSpecial: true,
    ingredients: ["Mixed Vegetables", "Fruits", "Nuts", "Cream", "Mild Spices"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "22 mins"
  },

  // ─── SPL. PANEER CURRIES ──────────────────────────────────────────────────
  {
    id: "spl-paneer-1",
    title: "Kundan Paneer",
    teluguTitle: "కుందన్ పనీర్",
    category: "SPL. PANEER CURRIES",
    description: "A rich, golden 'jewel' paneer curry cooked in saffron and cream gravy — a royal treat.",
    price: 350,
    rating: 4.7,
    image: "/images/kundan-paneer.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Saffron", "Cream", "Cashew Paste", "Royal Spices"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "22 mins"
  },
  {
    id: "spl-paneer-2",
    title: "Malai Methi Paneer",
    teluguTitle: "మలాయ్ మేతీ పనీర్",
    category: "SPL. PANEER CURRIES",
    description: "Paneer in a rich malai gravy with fresh fenugreek leaves — creamy, aromatic, indulgent.",
    price: 350,
    rating: 4.6,
    image: "/images/malai-methi-paneer.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Cream", "Fenugreek Leaves", "Butter"],
    allergens: ["Dairy"],
    prepTime: "22 mins"
  },
  {
    id: "spl-paneer-3",
    title: "Sangai Paneer",
    teluguTitle: "సంగాయ్ పనీర్",
    category: "SPL. PANEER CURRIES",
    description: "A unique chef's creation — paneer in a special north-eastern inspired gravy.",
    price: 350,
    rating: 4.6,
    image: "/images/sangai-paneer.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Special Masala", "Cream", "Herbs"],
    allergens: ["Dairy"],
    prepTime: "22 mins"
  },
  {
    id: "spl-paneer-4",
    title: "Paneer Kasha Masala",
    teluguTitle: "పనీర్ కషా మసాలా",
    category: "SPL. PANEER CURRIES",
    description: "Slow-cooked paneer in a thick, intense Bengali-style kasha masala — bold and robust.",
    price: 350,
    rating: 4.6,
    image: "/images/paneer-kasha-masala.png",
    isChefSpecial: true,
    ingredients: ["Paneer", "Kasha Masala", "Onion", "Ginger-Garlic"],
    allergens: ["Dairy"],
    prepTime: "22 mins"
  },
  {
    id: "spl-paneer-5",
    title: "ZilMil Paneer",
    teluguTitle: "జిల్మిల్ పనీర్",
    category: "SPL. PANEER CURRIES",
    description: "Chef's signature ZilMil paneer — a sparkling, multi-layered flavour experience.",
    price: 350,
    rating: 4.8,
    image: "/images/zilmil-paneer.png",
    isChefSpecial: true,
    ingredients: ["Paneer", "ZilMil Special Spices", "Cream", "Herbs"],
    allergens: ["Dairy"],
    prepTime: "24 mins"
  },

  // ─── SPL. VEG CURRIES ─────────────────────────────────────────────────────
  {
    id: "spl-veg-1",
    title: "Veg. Mandakini",
    teluguTitle: "వెజ్ మందాకిని",
    category: "SPL. VEG. CURRIES",
    description: "Seasonal vegetables in a divine, mild and aromatic special gravy — pure bliss.",
    price: 340,
    rating: 4.5,
    image: "/images/veg-mandakini.jpg",
    isChefSpecial: true,
    ingredients: ["Mixed Vegetables", "Aromatic Gravy", "Special Spices"],
    prepTime: "22 mins"
  },
  {
    id: "spl-veg-2",
    title: "Kandari Veg.",
    teluguTitle: "కందారీ వెజ్",
    category: "SPL. VEG. CURRIES",
    description: "Colourful seasonal vegetables in a rich restaurant-style special gravy.",
    price: 340,
    rating: 4.4,
    image: "/images/kandhari-veg.png",
    isChefSpecial: true,
    ingredients: ["Seasonal Vegetables", "Kandari Gravy"],
    prepTime: "22 mins"
  },
  {
    id: "spl-veg-3",
    title: "Haryali Methi Chaman",
    teluguTitle: "హర్యాలి మేతీ చమ్మన్",
    category: "SPL. VEG. CURRIES",
    description: "Paneer in a lush green haryali (spinach-mint-fenugreek) gravy — vibrant and fresh.",
    price: 320,
    rating: 4.5,
    image: "/images/hariyali-methi-chaman.jpg",
    isChefSpecial: true,
    ingredients: ["Paneer", "Spinach", "Mint", "Fenugreek", "Cream"],
    allergens: ["Dairy"],
    prepTime: "22 mins"
  },
  {
    id: "spl-veg-4",
    title: "ZilMil Veg.",
    teluguTitle: "జిల్మిల్ వెజ్",
    category: "SPL. VEG. CURRIES",
    description: "Mixed vegetables in our signature ZilMil special sauce — vibrant, layered flavours.",
    price: 340,
    rating: 4.6,
    image: "/images/zilmil-veg.png",
    isChefSpecial: true,
    ingredients: ["Mixed Vegetables", "ZilMil Sauce", "Special Spices"],
    prepTime: "22 mins"
  },

  // ─── ROTI / NAAN / PARATHA ────────────────────────────────────────────────
  {
    id: "roti-1",
    title: "Tandoori Roti",
    teluguTitle: "తందూరీ రొట్టె",
    category: "ROTI",
    description: "Classic whole wheat flatbread baked directly in a traditional clay tandoor oven.",
    price: 30,
    rating: 4.3,
    image: "/images/tandoori-roti.jpg",
    ingredients: ["Whole Wheat Flour", "Water", "Salt"],
    allergens: ["Gluten"],
    prepTime: "5 mins"
  },
  {
    id: "roti-2",
    title: "Butter Roti",
    teluguTitle: "బటర్ రొట్టె",
    category: "ROTI",
    description: "Whole wheat tandoori roti brushed generously with fresh dairy butter.",
    price: 35,
    rating: 4.5,
    image: "/images/butter-roti.jpg",
    isPopular: true,
    ingredients: ["Whole Wheat Flour", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "5 mins"
  },
  {
    id: "roti-3",
    title: "Kothmir Roti",
    teluguTitle: "కొత్తిమీర రొట్టె",
    category: "ROTI",
    description: "Whole wheat roti studded with fresh coriander leaves for a fragrant, herby flavour.",
    price: 35,
    rating: 4.2,
    image: "/images/kothmir-roti.jpg",
    ingredients: ["Whole Wheat Flour", "Coriander Leaves"],
    allergens: ["Gluten"],
    prepTime: "5 mins"
  },
  {
    id: "roti-4",
    title: "Kothmir Butter Roti",
    teluguTitle: "కొత్తిమీర బటర్ రొట్టె",
    category: "ROTI",
    description: "Coriander-infused roti brushed with butter — fresh herbs meet pure richness.",
    price: 40,
    rating: 4.3,
    image: "/images/kothmir-butter-roti.jpg",
    ingredients: ["Whole Wheat Flour", "Coriander", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "5 mins"
  },
  {
    id: "roti-5",
    title: "Pudina Roti",
    teluguTitle: "పుదీనా రొట్టె",
    category: "ROTI",
    description: "Whole wheat roti kneaded with fresh mint leaves for a cool, refreshing taste.",
    price: 35,
    rating: 4.2,
    image: "/images/pudina-roti.jpg",
    ingredients: ["Whole Wheat Flour", "Mint Leaves"],
    allergens: ["Gluten"],
    prepTime: "5 mins"
  },
  {
    id: "roti-6",
    title: "Pudina Butter Roti",
    teluguTitle: "పుదీనా బటర్ రొట్టె",
    category: "ROTI",
    description: "Mint roti brushed with butter — refreshing mint and rich butter in every bite.",
    price: 40,
    rating: 4.3,
    image: "/images/pudina-butter-roti.png",
    ingredients: ["Whole Wheat Flour", "Mint", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "5 mins"
  },
  {
    id: "roti-7",
    title: "Rumali Roti",
    teluguTitle: "రుమాలీ రొట్టె",
    category: "ROTI",
    description: "Paper-thin handkerchief bread cooked on an upside-down griddle — soft, light, delicate.",
    price: 55,
    rating: 4.4,
    image: "/images/rumali-roti.jpg",
    ingredients: ["Refined Flour", "Whole Wheat Flour", "Salt"],
    allergens: ["Gluten"],
    prepTime: "8 mins"
  },
  {
    id: "naan-1",
    title: "Plain Naan",
    teluguTitle: "ప్లెయిన్ నాన్",
    category: "NAAN",
    description: "Soft, leavened white flour bread baked in the clay tandoor — fluffy and pillowy.",
    price: 50,
    rating: 4.2,
    image: "/images/plain-naan.jpg",
    ingredients: ["Refined Flour", "Yeast", "Yoghurt"],
    allergens: ["Gluten", "Dairy"],
    prepTime: "6 mins"
  },
  {
    id: "naan-2",
    title: "Butter Naan",
    teluguTitle: "బటర్ నాన్",
    category: "NAAN",
    description: "Super soft leavened flatbread baked in clay tandoor, brushed generously with pure butter.",
    price: 55,
    rating: 4.6,
    image: "/images/butter-naan.jpg",
    isPopular: true,
    ingredients: ["Refined Flour", "Milk", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "6 mins"
  },
  {
    id: "naan-3",
    title: "Kothmir Naan",
    teluguTitle: "కొత్తిమీర నాన్",
    category: "NAAN",
    description: "Tandoor-baked naan with fresh coriander leaves embedded in every bite.",
    price: 55,
    rating: 4.3,
    image: "/images/kothmir-naan.jpg",
    ingredients: ["Refined Flour", "Coriander", "Yoghurt"],
    allergens: ["Gluten", "Dairy"],
    prepTime: "6 mins"
  },
  {
    id: "naan-4",
    title: "Kothmir Butter Naan",
    teluguTitle: "కొత్తిమీర బటర్ నాన్",
    category: "NAAN",
    description: "Coriander-topped naan brushed with butter — herby and rich.",
    price: 60,
    rating: 4.4,
    image: "/images/kothmir-butter-naan.jpg",
    ingredients: ["Refined Flour", "Coriander", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "6 mins"
  },
  {
    id: "naan-5",
    title: "Pudina Naan",
    teluguTitle: "పుదీనా నాన్",
    category: "NAAN",
    description: "Naan baked with fresh mint leaves for a refreshing cooling flavour.",
    price: 55,
    rating: 4.3,
    image: "/images/pudina-naan.png",
    ingredients: ["Refined Flour", "Mint", "Yoghurt"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "6 mins"
  },
  {
    id: "naan-6",
    title: "Pudina Butter Naan",
    teluguTitle: "పుదీనా బటర్ నాన్",
    category: "NAAN",
    description: "Mint-flavoured naan glazed with butter — the perfect bread companion.",
    price: 60,
    rating: 4.4,
    image: "/images/pudina-butter-naan.jpg",
    ingredients: ["Refined Flour", "Mint", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "6 mins"
  },
  {
    id: "naan-7",
    title: "Garlic Butter Naan",
    teluguTitle: "గార్లిక్ బటర్ నాన్",
    category: "NAAN",
    description: "Clay-oven baked naan infused with aromatic garlic and coriander, glazed with butter.",
    price: 75,
    rating: 4.7,
    image: "/images/garlic-butter-naan.jpg",
    isPopular: true,
    ingredients: ["Refined Flour", "Minced Garlic", "Coriander", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "6 mins"
  },
  {
    id: "naan-8",
    title: "Baby Naan",
    teluguTitle: "బేబీ నాన్",
    category: "NAAN",
    description: "A smaller, bite-sized version of the classic naan — perfect for kids or light appetites.",
    price: 65,
    rating: 4.2,
    image: "/images/baby-naan.jpg",
    ingredients: ["Refined Flour", "Yoghurt", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "5 mins"
  },
  {
    id: "naan-9",
    title: "Chatpata Naan",
    teluguTitle: "చట్పటా నాన్",
    category: "NAAN",
    description: "Naan with a chatpata spice topping — tangy, spicy and addictive.",
    price: 75,
    rating: 4.4,
    image: "/images/chatpata-naan.jpg",
    ingredients: ["Refined Flour", "Chaat Masala", "Amchoor", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "6 mins"
  },
  {
    id: "naan-10",
    title: "Kashmiri Naan",
    teluguTitle: "కాశ్మీరీ నాన్",
    category: "NAAN",
    description: "Fluffy naan filled with nuts and dried fruits — mildly sweet and absolutely indulgent.",
    price: 75,
    rating: 4.5,
    image: "/images/kashmiri-naan.jpg",
    ingredients: ["Refined Flour", "Dry Fruits", "Nuts", "Sugar"],
    allergens: ["Dairy", "Gluten", "Nuts"],
    prepTime: "8 mins"
  },
  {
    id: "naan-11",
    title: "Stuff Naan",
    teluguTitle: "స్టఫ్ నాన్",
    category: "NAAN",
    description: "Naan stuffed with a spiced paneer or veggie filling — a complete meal in a bread.",
    price: 75,
    rating: 4.5,
    image: "/images/stuff-naan.jpg",
    ingredients: ["Refined Flour", "Paneer Stuffing", "Spices"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "10 mins"
  },
  {
    id: "paratha-1",
    title: "Alu Paratha",
    teluguTitle: "ఆలూ పరాటా",
    category: "PARATHA in TANDOOR",
    description: "Whole wheat bread stuffed with seasoned mashed potatoes, roasted on a griddle.",
    price: 75,
    rating: 4.5,
    image: "/images/alu-paratha.jpg",
    isPopular: true,
    ingredients: ["Whole Wheat Flour", "Potato Stuffing", "Spices", "Ghee"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "10 mins"
  },
  {
    id: "paratha-2",
    title: "Pudina Paratha",
    teluguTitle: "పుదీనా పరాటా",
    category: "PARATHA in TANDOOR",
    description: "Layered whole wheat paratha with fresh mint leaves — light and fragrant.",
    price: 75,
    rating: 4.3,
    image: "/images/pudina-paratha.jpg",
    ingredients: ["Whole Wheat Flour", "Mint", "Ghee"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "8 mins"
  },
  {
    id: "paratha-3",
    title: "Paneer Paratha",
    teluguTitle: "పనీర్ పరాటా",
    category: "PARATHA in TANDOOR",
    description: "Whole wheat paratha stuffed with spiced grated paneer — rich, filling and delicious.",
    price: 80,
    rating: 4.6,
    image: "/images/paneer-paratha.png",
    ingredients: ["Whole Wheat Flour", "Grated Paneer", "Spices", "Ghee"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "10 mins"
  },
  {
    id: "paratha-4",
    title: "Lacha Paratha",
    teluguTitle: "లచ్చా పరాటా",
    category: "PARATHA in TANDOOR",
    description: "Flaky, layered whole wheat paratha cooked in a griddle — perfectly crispy on the outside.",
    price: 65,
    rating: 4.4,
    image: "/images/lacha-paratha.jpg",
    isPopular: true,
    ingredients: ["Whole Wheat Flour", "Ghee", "Salt"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "8 mins"
  },
  {
    id: "paratha-5",
    title: "Rajsthani Methi Paratha",
    teluguTitle: "రాజస్థాని మేతీ పరాటా",
    category: "PARATHA in TANDOOR",
    description: "Rajasthani-style paratha with fresh fenugreek leaves kneaded into the dough.",
    price: 75,
    rating: 4.3,
    image: "/images/rajasthani-methi-paratha.jpg",
    ingredients: ["Whole Wheat Flour", "Fenugreek Leaves", "Ghee", "Spices"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "10 mins"
  },
  {
    id: "kulcha-1",
    title: "Masala Kulcha",
    teluguTitle: "మసాలా కుల్చా",
    category: "PARATHA in TANDOOR",
    description: "Soft, fluffy leavened kulcha stuffed with a spiced vegetable masala filling.",
    price: 80,
    rating: 4.4,
    image: "/images/masala-kulcha.png",
    ingredients: ["Refined Flour", "Spiced Stuffing", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "10 mins"
  },
  {
    id: "kulcha-2",
    title: "Paneer Kulcha",
    teluguTitle: "పనీర్ కుల్చా",
    category: "PARATHA in TANDOOR",
    description: "Fluffy kulcha stuffed with spiced grated paneer — great with any dal or curry.",
    price: 80,
    rating: 4.5,
    image: "/images/paneer-kulcha.png",
    ingredients: ["Refined Flour", "Paneer Stuffing", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "10 mins"
  },
  {
    id: "kulcha-3",
    title: "Stuff Kulcha",
    teluguTitle: "స్టఫ్ కుల్చా",
    category: "PARATHA in TANDOOR",
    description: "Kulcha stuffed with a special mixed filling of your choice — soft and satisfying.",
    price: 90,
    rating: 4.4,
    image: "/images/stuff-kulcha.png",
    ingredients: ["Refined Flour", "Special Stuffing", "Butter"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "10 mins"
  },

  // ─── RICE ─────────────────────────────────────────────────────────────────
  {
    id: "rice-1",
    title: "Plain Rice",
    teluguTitle: "సాదా అన్నం",
    category: "RICE",
    description: "Simple, perfectly cooked steamed Basmati rice — the ideal accompaniment.",
    price: 190,
    rating: 4.1,
    image: "/images/plain-rice.jpg",
    ingredients: ["Basmati Rice", "Water", "Salt"],
    prepTime: "15 mins"
  },
  {
    id: "rice-2",
    title: "Curd Rice",
    teluguTitle: "పెరుగు అన్నం",
    category: "RICE",
    description: "Creamy, comforting curd rice with a tadka of mustard, curry leaves and ginger.",
    price: 220,
    rating: 4.3,
    image: "/images/curd-rice.png",
    ingredients: ["Rice", "Curd", "Mustard", "Curry Leaves", "Ginger"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "rice-3",
    title: "Lemon Rice",
    teluguTitle: "నిమ్మ అన్నం",
    category: "RICE",
    description: "Tangy lemon rice with mustard, curry leaves, green chilli and turmeric.",
    price: 210,
    rating: 4.2,
    image: "/images/lemon-rice.png",
    ingredients: ["Rice", "Lemon", "Mustard", "Curry Leaves", "Turmeric"],
    prepTime: "15 mins"
  },
  {
    id: "rice-4",
    title: "Butter Rice",
    teluguTitle: "బటర్ అన్నం",
    category: "RICE",
    description: "Fluffy Basmati rice cooked with butter for a rich, mellow flavour.",
    price: 210,
    rating: 4.2,
    image: "/images/butter-rice.png",
    ingredients: ["Basmati Rice", "Butter"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "rice-5",
    title: "Jeera Rice",
    teluguTitle: "జీరా రైస్",
    category: "RICE",
    description: "Aromatic Basmati rice tempered with whole cumin seeds in ghee — simple and fragrant.",
    price: 250,
    rating: 4.4,
    image: "/images/jeera-rice.png",
    ingredients: ["Basmati Rice", "Cumin Seeds", "Ghee"],
    allergens: ["Dairy"],
    prepTime: "15 mins"
  },
  {
    id: "rice-6",
    title: "Tomato Rice",
    teluguTitle: "టొమాటో రైస్",
    category: "RICE",
    description: "Tangy and spiced rice cooked with fresh tomatoes, onions and South Indian spices.",
    price: 250,
    rating: 4.2,
    image: "/images/tomato-rice.png",
    ingredients: ["Rice", "Tomatoes", "Onion", "Spices", "Curry Leaves"],
    prepTime: "18 mins"
  },
  {
    id: "rice-7",
    title: "Kaju Jeera Rice",
    teluguTitle: "కాజు జీరా రైస్",
    category: "RICE",
    description: "Jeera rice elevated with golden roasted whole cashews — nutty and aromatic.",
    price: 270,
    rating: 4.5,
    image: "/images/kaju-jeera-rice.png",
    ingredients: ["Basmati Rice", "Cumin", "Cashew Nuts", "Ghee"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "15 mins"
  },

  // ─── FRIED RICE ───────────────────────────────────────────────────────────
  {
    id: "fried-rice-1",
    title: "Veg. Fried Rice",
    teluguTitle: "వెజ్ ఫ్రైడ్ రైస్",
    category: "FRIED RICE",
    description: "Classic Indo-Chinese fried rice with mixed vegetables, soy and garlic.",
    price: "250 / 220",
    rating: 4.2,
    image: "/images/veg-fried-rice.png",
    ingredients: ["Rice", "Mixed Vegetables", "Soy Sauce", "Garlic"],
    allergens: ["Soy"],
    prepTime: "15 mins"
  },
  {
    id: "fried-rice-2",
    title: "Paneer Fried Rice",
    teluguTitle: "పనీర్ ఫ్రైడ్ రైస్",
    category: "FRIED RICE",
    description: "Fried rice with paneer cubes, vegetables and savory soy sauce.",
    price: 270,
    rating: 4.3,
    image: "/images/paneer-fried-rice.png",
    ingredients: ["Rice", "Paneer", "Vegetables", "Soy Sauce"],
    allergens: ["Dairy", "Soy"],
    prepTime: "16 mins"
  },
  {
    id: "fried-rice-3",
    title: "Schezwan Fried Rice",
    teluguTitle: "షెజ్వాన్ ఫ్రైడ్ రైస్",
    category: "FRIED RICE",
    description: "Spicy Schezwan fried rice — fiery, fragrant and packed with flavour.",
    price: 270,
    rating: 4.4,
    image: "/images/schezwan-fried-rice.jpg",
    isPopular: true,
    ingredients: ["Rice", "Schezwan Sauce", "Mixed Vegetables", "Garlic"],
    allergens: ["Soy"],
    prepTime: "16 mins"
  },
  {
    id: "fried-rice-4",
    title: "Masala Fried Rice",
    teluguTitle: "మసాలా ఫ్రైడ్ రైస్",
    category: "FRIED RICE",
    description: "Fried rice tossed in an aromatic Indian masala spice blend.",
    price: 290,
    rating: 4.2,
    image: "/images/masala-fried-rice.jpg",
    ingredients: ["Rice", "Masala Spices", "Mixed Vegetables"],
    prepTime: "16 mins"
  },
  {
    id: "fried-rice-5",
    title: "Kaju Fried Rice",
    teluguTitle: "కాజు ఫ్రైడ్ రైస్",
    category: "FRIED RICE",
    description: "Fried rice with whole roasted cashews, vegetables and mild seasonings.",
    price: 290,
    rating: 4.4,
    image: "/images/kaju-fried-rice.jpg",
    ingredients: ["Rice", "Cashew Nuts", "Mixed Vegetables", "Soy Sauce"],
    allergens: ["Nuts", "Soy"],
    prepTime: "16 mins"
  },

  // ─── PULAOS ───────────────────────────────────────────────────────────────
  {
    id: "pullaw-1",
    title: "Veg. Pulao",
    teluguTitle: "వెజ్ పులావ్",
    category: "PULAO",
    description: "Aromatic Basmati rice cooked with seasonal vegetables and whole spices.",
    price: "260 / 210",
    rating: 4.2,
    image: "/images/veg-pulao.jpg",
    ingredients: ["Basmati Rice", "Mixed Vegetables", "Whole Spices", "Ghee"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "pullaw-2",
    title: "Corn Kaju Pulao",
    teluguTitle: "కార్న్ కాజు పులావ్",
    category: "PULAO",
    description: "Sweet corn and cashew rice cooked with mild spices — mildly sweet and nutty.",
    price: 300,
    rating: 4.3,
    image: "/images/corn-kaju-pulao.jpg",
    ingredients: ["Basmati Rice", "Sweet Corn", "Cashews", "Spices"],
    allergens: ["Nuts"],
    prepTime: "20 mins"
  },
  {
    id: "pullaw-3",
    title: "Kashmiri Pulao (Sweet)",
    teluguTitle: "కాశ్మీరీ పులావ్",
    category: "PULAO",
    description: "Fragrant saffron rice with dry fruits, nuts and a mild sweetness — a royal treat.",
    price: 300,
    rating: 4.5,
    image: "/images/kashmiri-pulao.jpg",
    isChefSpecial: true,
    ingredients: ["Basmati Rice", "Saffron", "Dry Fruits", "Nuts", "Ghee"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "22 mins"
  },
  {
    id: "pullaw-4",
    title: "Navratan Pulao (Sweet)",
    teluguTitle: "నవరతన్ పులావ్",
    category: "PULAO",
    description: "Nine-gem pulao with assorted vegetables, fruits and nuts in a fragrant rice.",
    price: 300,
    rating: 4.4,
    image: "/images/navratan-pulao.jpg",
    ingredients: ["Rice", "Mixed Veggies", "Dry Fruits", "Nuts"],
    allergens: ["Nuts"],
    prepTime: "22 mins"
  },
  {
    id: "pullaw-5",
    title: "Punjabi Pulao",
    teluguTitle: "పంజాబీ పులావ్",
    category: "PULAO",
    description: "Hearty Punjabi-style rice cooked with vegetables and robust dhaba spices.",
    price: 300,
    rating: 4.3,
    image: "/images/punjabi-pulao.jpg",
    ingredients: ["Basmati Rice", "Punjabi Spices", "Vegetables", "Ghee"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },
  {
    id: "pullaw-6",
    title: "Paneer Pulao",
    teluguTitle: "పనీర్ పులావ్",
    category: "PULAO",
    description: "Fragrant Basmati rice cooked with paneer cubes and aromatic whole spices.",
    price: 300,
    rating: 4.4,
    image: "/images/paneer-pulao.jpg",
    ingredients: ["Basmati Rice", "Paneer", "Whole Spices", "Ghee"],
    allergens: ["Dairy"],
    prepTime: "20 mins"
  },

  // ─── BIRYANIS ─────────────────────────────────────────────────────────────
  {
    id: "biryani-1",
    title: "Veg. Biryani",
    teluguTitle: "వెజ్ బిర్యానీ",
    category: "BIRYANI",
    description: "Fragrant Basmati rice layered with seasonal vegetables, saffron and fried onions.",
    price: "290 / 220",
    rating: 4.4,
    image: "/images/veg-biryani.jpg",
    isPopular: true,
    ingredients: ["Basmati Rice", "Mixed Vegetables", "Saffron", "Fried Onions"],
    prepTime: "22 mins"
  },
  {
    id: "biryani-2",
    title: "Handi Biryani",
    teluguTitle: "హండి బిర్యానీ",
    category: "BIRYANI",
    description: "Biryani slow-cooked in a sealed clay handi for an intensely aromatic, smoky flavour.",
    price: 300,
    rating: 4.5,
    image: "/images/handi-biryani.jpg",
    isChefSpecial: true,
    ingredients: ["Basmati Rice", "Vegetables/Paneer", "Handi Dum Spices"],
    allergens: ["Dairy"],
    prepTime: "25 mins"
  },
  {
    id: "biryani-3",
    title: "Dum Biryani",
    teluguTitle: "దమ్ బిర్యానీ",
    category: "BIRYANI",
    description: "Authentic Dum-style biryani slow-cooked under a sealed lid for maximum flavour.",
    price: 300,
    rating: 4.5,
    image: "/images/dum-biryani.jpg",
    ingredients: ["Basmati Rice", "Dum Spices", "Saffron", "Rose Water"],
    allergens: ["Dairy"],
    prepTime: "25 mins"
  },
  {
    id: "biryani-4",
    title: "Paneer Biryani",
    teluguTitle: "పనీర్ బిర్యానీ",
    category: "BIRYANI",
    description: "Layers of long-grain Basmati rice with marinated paneer, saffron and fried onions.",
    price: "310 / 240",
    rating: 4.6,
    image: "/images/paneer-biryani.jpg",
    isPopular: true,
    ingredients: ["Basmati Rice", "Paneer", "Saffron", "Rose Water", "Biryani Spices"],
    allergens: ["Dairy"],
    prepTime: "22 mins"
  },
  {
    id: "biryani-5",
    title: "Kaju Biryani",
    teluguTitle: "కాజు బిర్యానీ",
    category: "BIRYANI",
    description: "Fragrant Basmati slow-cooked with premium cashews, rich spices and herbs.",
    price: 320,
    rating: 4.4,
    image: "/images/kaju-biryani.jpg",
    ingredients: ["Basmati Rice", "Cashew Nuts", "Brown Onions", "Cardamom", "Ghee"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "22 mins"
  },
  {
    id: "biryani-6",
    title: "Hyderabadi Biryani",
    teluguTitle: "హైదరాబాదీ బిర్యానీ",
    category: "BIRYANI",
    description: "Iconic Hyderabadi dum biryani with aromatic kewra, saffron and home-ground masala.",
    price: 320,
    rating: 4.7,
    image: "/images/hyderabadi-biryani.jpg",
    isChefSpecial: true,
    isPopular: true,
    isSignature: true,
    ingredients: ["Basmati Rice", "Hyderabadi Masala", "Saffron", "Kewra", "Fried Onions"],
    allergens: ["Dairy"],
    prepTime: "28 mins"
  },
  {
    id: "biryani-7",
    title: "Mushroom Biryani",
    teluguTitle: "మష్రూమ్ బిర్యానీ",
    category: "BIRYANI",
    description: "Earthy mushrooms with Basmati rice in an aromatic biryani — umami-rich and satisfying.",
    price: 340,
    rating: 4.4,
    image: "/images/mushroom-biryani.jpg",
    ingredients: ["Basmati Rice", "Button Mushrooms", "Biryani Spices", "Fried Onions"],
    prepTime: "22 mins"
  },
  {
    id: "biryani-8",
    title: "Kaju Paneer Biryani",
    teluguTitle: "కాజు పనీర్ బిర్యానీ",
    category: "BIRYANI",
    description: "Our signature biryani combining crispy golden cashews and tender paneer — the ultimate.",
    price: 330,
    rating: 4.8,
    image: "/images/kaju-paneer-biryani.jpg",
    isChefSpecial: true,
    ingredients: ["Basmati Rice", "Paneer", "Cashew Nuts", "Dum Spices", "Kevra Water"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "24 mins"
  },

  // ─── PAPAD ────────────────────────────────────────────────────────────────
  {
    id: "papad-1",
    title: "Roasted Papad",
    teluguTitle: "రోస్టెడ్ పాపడ్",
    category: "PAPAD",
    description: "Light and crispy roasted lentil wafer — a classic appetiser before your meal.",
    price: 40,
    rating: 4.1,
    image: "/images/roasted-papad.jpg",
    ingredients: ["Lentil Wafer"],
    prepTime: "3 mins"
  },
  {
    id: "papad-2",
    title: "Fry Papad",
    teluguTitle: "ఫ్రై పాపడ్",
    category: "PAPAD",
    description: "Crispy deep-fried lentil wafer — golden, light and utterly addictive.",
    price: 40,
    rating: 4.2,
    image: "/images/fry-papad.jpg",
    ingredients: ["Lentil Wafer", "Oil"],
    prepTime: "3 mins"
  },
  {
    id: "papad-3",
    title: "Butter Papad",
    teluguTitle: "బటర్ పాపడ్",
    category: "PAPAD",
    description: "Crispy roasted papad brushed with butter — simple pleasure elevated.",
    price: 45,
    rating: 4.2,
    image: "/images/butter-papad.jpg",
    ingredients: ["Lentil Wafer", "Butter"],
    allergens: ["Dairy"],
    prepTime: "3 mins"
  },
  {
    id: "papad-4",
    title: "Masala Papad",
    teluguTitle: "మసాలా పాపడ్",
    category: "PAPAD",
    description: "Crispy papad topped with fresh onions, tomatoes, coriander and chaat masala.",
    price: 55,
    rating: 4.4,
    image: "/images/masala-papad.jpg",
    isPopular: true,
    ingredients: ["Lentil Wafer", "Onion", "Tomato", "Coriander", "Chaat Masala"],
    prepTime: "5 mins"
  },
  {
    id: "papad-5",
    title: "Spl. Punjabi Papad",
    teluguTitle: "స్పెషల్ పంజాబీ పాపడ్",
    category: "PAPAD",
    description: "Special Punjabi-style masala papad with extra toppings and a chatpata kick.",
    price: 85,
    rating: 4.5,
    image: "/images/special-punjabi-papad.jpg",
    isChefSpecial: true,
    ingredients: ["Lentil Wafer", "Special Punjabi Topping", "Chaat Masala", "Green Chilli"],
    prepTime: "5 mins"
  },

  // ─── RAITA ────────────────────────────────────────────────────────────────
  {
    id: "raita-1",
    title: "Mix Raita",
    teluguTitle: "మిక్స్ రాయతా",
    category: "RAITA",
    description: "Chilled yoghurt mixed with cucumber, tomato, onion and mild spices.",
    price: 60,
    rating: 4.2,
    image: "/images/mix-raita.jpg",
    ingredients: ["Yoghurt", "Cucumber", "Tomato", "Onion", "Cumin"],
    allergens: ["Dairy"],
    prepTime: "5 mins"
  },
  {
    id: "raita-2",
    title: "Onion Raita",
    teluguTitle: "ఉల్లి రాయతా",
    category: "RAITA",
    description: "Refreshing yoghurt with thinly sliced onions, coriander and roasted cumin.",
    price: 60,
    rating: 4.1,
    image: "/images/onion-raita.jpg",
    ingredients: ["Yoghurt", "Onion", "Coriander", "Cumin"],
    allergens: ["Dairy"],
    prepTime: "5 mins"
  },
  {
    id: "raita-3",
    title: "Boondi Raita",
    teluguTitle: "బూందీ రాయతా",
    category: "RAITA",
    description: "Creamy yoghurt with crunchy boondi pearls, cumin and mild red chilli.",
    price: 70,
    rating: 4.3,
    image: "/images/boondi-raita.jpg",
    isPopular: true,
    ingredients: ["Yoghurt", "Boondi", "Cumin", "Red Chilli Powder"],
    allergens: ["Dairy", "Gluten"],
    prepTime: "5 mins"
  },
  {
    id: "raita-4",
    title: "Curd (Dahi)",
    teluguTitle: "పెరుగు",
    category: "RAITA",
    description: "Fresh, chilled natural yoghurt — plain and simple.",
    price: 65,
    rating: 4.1,
    image: "/images/curd-dahi.jpg",
    ingredients: ["Fresh Curd"],
    allergens: ["Dairy"],
    prepTime: "2 mins"
  },

  // ─── SOFT DRINKS / BEVERAGES ──────────────────────────────────────────────
  {
    id: "bev-1",
    title: "Sweet Lassi",
    teluguTitle: "స్వీట్ లస్సీ",
    category: "SOFT DRINKS",
    description: "Creamy chilled yoghurt shake sweetened with sugar, flavoured with cardamom.",
    price: "80 / 100",
    rating: 4.5,
    image: "/images/sweet-lassi.jpg",
    isPopular: true,
    ingredients: ["Yoghurt", "Sugar", "Cardamom", "Pistachio garnish"],
    allergens: ["Dairy", "Nuts"],
    prepTime: "5 mins"
  },
  {
    id: "bev-2",
    title: "Salted Lassi",
    teluguTitle: "సాల్టెడ్ లస్సీ",
    category: "SOFT DRINKS",
    description: "Savoury chilled yoghurt drink with a pinch of roasted cumin and black salt.",
    price: "80 / 100",
    rating: 4.2,
    image: "/images/salted-lassi.jpg",
    ingredients: ["Yoghurt", "Black Salt", "Roasted Cumin"],
    allergens: ["Dairy"],
    prepTime: "5 mins"
  },
  {
    id: "bev-3",
    title: "Butter Milk",
    teluguTitle: "మజ్జిగ",
    category: "SOFT DRINKS",
    description: "Chilled, light buttermilk with roasted cumin, ginger and fresh coriander.",
    price: "60 / 80",
    rating: 4.2,
    image: "/images/butter-milk.jpg",
    ingredients: ["Yoghurt", "Water", "Cumin", "Ginger", "Coriander"],
    allergens: ["Dairy"],
    prepTime: "5 mins"
  },
  {
    id: "bev-4",
    title: "Cold Drinks (300ml)",
    teluguTitle: "కోల్డ్ డ్రింక్స్",
    category: "SOFT DRINKS",
    description: "Choice of popular cold beverages — Pepsi, 7Up, Mirinda or Mountain Dew.",
    price: 40,
    rating: 4.0,
    image: "/images/cold-drinks.jpg",
    ingredients: ["Carbonated Beverage"],
    prepTime: "2 mins"
  },
  {
    id: "bev-5",
    title: "Mineral Water",
    teluguTitle: "మినరల్ వాటర్",
    category: "SOFT DRINKS",
    description: "Chilled purified mineral water to keep you refreshed.",
    price: 20,
    rating: 4.0,
    image: "/images/mineral-water.jpg",
    ingredients: ["Purified Water"],
    prepTime: "1 min"
  },
  {
    id: "bev-6",
    title: "Fresh Lime Soda (Sweet)",
    teluguTitle: "లైమ్ సోడా స్వీట్",
    category: "SOFT DRINKS",
    description: "Freshly squeezed lime with sparkling soda and sugar — refreshing and zingy.",
    price: 70,
    rating: 4.4,
    image: "/images/fresh-lime-soda-sweet.jpg",
    isPopular: true,
    ingredients: ["Fresh Lime", "Soda Water", "Sugar"],
    prepTime: "5 mins"
  },
  {
    id: "bev-7",
    title: "Fresh Lime Soda (Salted)",
    teluguTitle: "లైమ్ సోడా సాల్ట్",
    category: "SOFT DRINKS",
    description: "Freshly squeezed lime with sparkling soda, black salt and roasted cumin.",
    price: 70,
    rating: 4.3,
    image: "/images/fresh-lime-soda-salted.jpg",
    ingredients: ["Fresh Lime", "Soda Water", "Black Salt", "Cumin"],
    prepTime: "5 mins"
  },

  // ─── JUMBO FAMILY PACK ────────────────────────────────────────────────────
  {
    id: "family-1",
    title: "Paneer Biryani (Family Pack)",
    teluguTitle: "పనీర్ బిర్యానీ ఫ్యామిలీ పాక్",
    category: "JUMBO FAMILY PACK",
    description: "Jumbo takeaway pack of our signature Paneer Biryani — perfect for the whole family.",
    price: 725,
    rating: 4.7,
    image: "/images/paneer-biryani-family.png",
    isChefSpecial: true,
    ingredients: ["Basmati Rice", "Paneer", "Biryani Spices", "Fried Onions"],
    allergens: ["Dairy"],
    prepTime: "30 mins"
  },
  {
    id: "family-2",
    title: "Mushroom Biryani (Family Pack)",
    teluguTitle: "మష్రూమ్ బిర్యానీ ఫ్యామిలీ పాక్",
    category: "JUMBO FAMILY PACK",
    description: "Jumbo takeaway pack of earthy Mushroom Biryani — feeds 4-5 people.",
    price: 725,
    rating: 4.5,
    image: "/images/mushroom-biryani-family.png",
    ingredients: ["Basmati Rice", "Mushrooms", "Biryani Spices"],
    prepTime: "30 mins"
  },
  {
    id: "family-3",
    title: "Veg. Biryani (Family Pack)",
    teluguTitle: "వెజ్ బిర్యానీ ఫ్యామిలీ పాక్",
    category: "JUMBO FAMILY PACK",
    description: "Jumbo takeaway pack of aromatic Veg Biryani — great value for the whole family.",
    price: 725,
    rating: 4.5,
    image: "/images/veg-biryani-family.jpg",
    ingredients: ["Basmati Rice", "Mixed Vegetables", "Biryani Spices", "Saffron"],
    prepTime: "30 mins"
  },

  // ─── COMBO FAMILY PACK ────────────────────────────────────────────────────
  {
    id: "combo-1",
    title: "Combo Family Pack",
    teluguTitle: "కాంబో ఫ్యామిలీ పాక్",
    category: "COMBO FAMILY PACK",
    description: "Veg. Manchuria + Paneer Butter Masala + Butter Roti (8pcs) + Veg. Biryani (Half) — complete family feast!",
    price: 899,
    rating: 4.8,
    image: "/images/combo-family-pack.jpg",
    isChefSpecial: true,
    isPopular: true,
    ingredients: ["Veg Manchurian", "Paneer Butter Masala", "Butter Roti x8", "Veg Biryani Half"],
    allergens: ["Dairy", "Gluten", "Soy"],
    prepTime: "35 mins"
  }
];
